name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install selenium
            pip install robotframework
            pip install robotframework-selenium2library
        - name: Execute tests
          uses: acontre200/robotframework@version1
          #joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/Tests
            REPORT_PATH: ${{ github.workspace }}/reports
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
            ROBOT_OPTIONS: -T -d ${{ github.workspace }}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
